---
- name: Create user on ansible and test hosts 
  hosts: ['ansible.local', 'test-3.local']
  become: yes
  tasks:

  - name: Create users
    ansible.builtin.user:
      name: esentemov_ansible
      groups: wheel

- name: Generate ssh-keys for new user and fill authorized_keys on ansible host
  hosts: ['ansible.local']
  become: yes
  gather_facts: no
  tasks:

  - name: Generate ssh_key on ansible host
    ansible.builtin.user:
      name: esentemov_ansible
      generate_ssh_key: yes

  - name: Transfer ssh-key to new user on ansible host
    authorized_key:
      user: esentemov_ansible
      state: present
      key: "{{ lookup('file', '/home/esentemov/.ssh/id_rsa.pub') }}"  

- name: Transfer ssh-key to test host and change sshd_config
  hosts: ['test-3.local']
  become: yes
  gather_facts: no
  tasks:

  - name: Transfer ssh-key to test host
    authorized_key:
      user: esentemov_ansible
      state: present
      key: "{{ lookup('file', '/home/esentemov/.ssh/id_rsa.pub') }}"

  - name: Change test's ssh_config
    lineinfile:
      dest: /etc/ssh/sshd_config
      backup: yes
      regexp: '^PasswordAuthentication '
      line: 'PasswordAuthentitication no'
      state: present

