---
- name: Add PostgreSQL Repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: installed

- name: Install Required Packages
  yum:
    name:
    - epel-release
    - yum-utils
    state: installed

- name: Enable PostgreSQL Repo
  shell: 
    'yum-config-manager --enable pgdg12'
#  yum_repository:
#    name: pgdg12
#    enabled: yes
#    baseurl: https://download.postgresql.org/pub/repos/yum/12/redhat/rhel-$releasever-$basearch

- name: Install PostgreSQL 12
  yum:
    name:
    - postgresql12-server
    - postgresql12
    state: installed

- name: Copy script
  copy:
    src: 2_postgres.sh
    dest: /root
    owner: root
    mode: '0744'

- name: Copy autoscript file
  copy:
    src: autoscript.txt
    dest: /root
    owner: root
    mode: '0644'

- name: Init DB
  shell: "/root/2_postgres.sh < /root/autoscript.txt"

- name: enable and start postgres service
  service:
    name               : postgresql-12
    state              : started
    enabled            : yes

#- name: Open socket for subnet
#  lineinfile:
#    path: /data/postgres/12/data/postgresql.conf
#    regexp: '^listen_addresses'
#    line: listen_addresses = '{{ ansible_default_ipv4.address }}'
#    state: present
